# 45장. 프로미스
자바스크립트는 비동기 처리를 위해한 하나의 패턴으로 콜백함수를 사용한다. 전통적인 콜백 패턴은 콜백헬로 인해 가독성이 나쁘고 발생한 에러의 처리가 어렵다.   
ES6에서 비동기 처리를 위한 또 다른 패턴으로 프로미스를 도입했다. 
## 45.1 비동기 처리를 위한 콜백 패턴의 단점
### 45.1.1 콜백 헬
```js
// GET 요청을 위한 비동기 함수
const get = url => {
  const xhr = new XMLHttpRequest()
  xhr.open('GET', url)
  xhr.send()

  xhr.onload = () => {
    if (xhr.status === 200) {
      // 서버의 응답을 콘솔에 출력한다.
      console.log(JSON.parse(xhr.response))
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`)
    }
  }
}

// id가 1인 post를 취득
get('https://jsonplaceholder.typicode.com/posts/1')
/*
{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere ...",
  "body": "quia et suscipit ..."
}
*/
```
get 함수는 비동기 함수다. 함수 내부에 비동기로 동작하는 코드를 포함한 함수로 **비동기 함수를 호출하면 함수 내부의 비동기로 동작하는 코드가 완료되지 않았다 해도 기다리지 않고 즉시 종료된다. 비동기 함수 내부의 비동기 코드는 비동기 함수가 종료된 이후 완료된다. 따라서 비동기 함수 내부의 비동기로 동작하는 코드에서 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않는다.**   
```js
let g = 0

// 비동기 함수인 setTimeout 함수는 콜백 함수의 처리 결과를 외부로 반환하거나
// 상위 스코프의 변수에 할당하지 못한다.
setTimeout(() => { g = 100 }, 0)
console.log(g) // 0
```
get 함수 내부의 onload 이벤트 핸들러가 비동기로 동작한다. get 함수를 호출하면 GET 요청을 전송하고 onload 이벤트 핸들러를 등록한 다음 indefined를 반환하고 즉시 종료된다. onload는 get 함수가 종료된 이후 실행된다. 따라서 get 함수의 onload 이벤트 핸들러에서 서버 응답 결과를 반환하거나 상위 스코프의 변수에 할당하면 기대한대로 동작하지 않는다.
```js
// GET 요청을 위한 비동기 함수
const get = url => {
  const xhr = new XMLHttpRequest()
  xhr.open('GET', url)
  xhr.send()

  xhr.onload = () => {
    if (xhr.status === 200) {
      // ① 서버의 응답을 반환한다.
      return JSON.parse(xhr.response)
    }
    console.error(`${xhr.status} ${xhr.statusText}`)
  }
}

// ② id가 1인 post를 취득
const response = get('https://jsonplaceholder.typicode.com/posts/1')
console.log(response) // undefined
```
xhr.onload 이벤트 핸들러 프로퍼티에 바인딩한 이벤트 핸들러 반환문(1)은 get 함수의 반환문이 아니다. get 함수는 반환문이 생략되었으므로 암묵적으로 undefined다. onload 이벤트 핸들러를 get 함수가 호출할 수 있다면 이벤트 핸들러의 반환 값을 get 함수가 캐치하여 다시 반환할 수 있지만 onload 이벤트 핸들러는 get 함수가 호출하지 않기 떄문에 그럴 수 없다.
```js
let todos

// GET 요청을 위한 비동기 함수
const get = url => {
  const xhr = new XMLHttpRequest()
  xhr.open('GET', url)
  xhr.send()

  xhr.onload = () => {
    if (xhr.status === 200) {
      // ① 서버의 응답을 상위 스코프의 변수에 할당한다.
      todos = JSON.parse(xhr.response)
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`)
    }
  }
}

// id가 1인 post를 취득
get('https://jsonplaceholder.typicode.com/posts/1')
console.log(todos) // ② undefined
```
1에서 서버 응답을 상위 스코프의 변수로 할당한다 해도 xhr.onload 이벤트 핸들러 프로퍼티에 바인딩한 이벤트 핸들러는 언제나 console.log가 종료한 후에 호출된다. 따라서 2의 시점에서는 아직 값이 할당되기 전이다. 
**비동기 함수는 비동기 처리 결과를 외부에 반환할 수 없고, 상위 스코프의 뱐수에 할당할 수도 없다. 비동기 함수의 처리 결과에 대한 후속 처리는 비동기 함수 내부에서 수행해야 한다. 비동기 함수를 범용적으로 사용하기 위해 비동기 함수에 비동기 처리 결과에 대한 후속 처리를 수행하는 콜백 함수를 전달하는 것이 일반적이다. 필요에 따라 비동기 처리가 성공하면 호출될 콜백 함수와 비동기 처리가 실패하면 호출될 콜백 함수를 전달할 수 잇다.**
```js
// GET 요청을 위한 비동기 함수
const get = (url, successCallback, failureCallback) => {
  const xhr = new XMLHttpRequest()
  xhr.open('GET', url)
  xhr.send()

  xhr.onload = () => {
    if (xhr.status === 200) {
      // 서버의 응답을 콜백 함수에 인수로 전달하면서 호출하여 응답에 대한 후속 처리를 한다.
      successCallback(JSON.parse(xhr.response))
    } else {
      // 에러 정보를 콜백 함수에 인수로 전달하면서 호출하여 에러 처리를 한다.
      failureCallback(xhr.status)
    }
  }
}

// id가 1인 post를 취득
// 서버의 응답에 대한 후속 처리를 위한 콜백 함수를 비동기 함수인 get에 전달해야 한다.
get('https://jsonplaceholder.typicode.com/posts/1', console.log, console.error)
/*
{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere ...",
  "body": "quia et suscipit ..."
}
*/
```
이는 비동기 처리 결과를 후속 처리를 수행하는 비동기 함수가 비동기 처리 결과를 가지고 또다시 비동기 함수를 호출해야 한다면 콜백이 중첩되는 **콜백 헬**이 발생한다.
```js
// GET 요청을 위한 비동기 함수
const get = (url, callback) => {
  const xhr = new XMLHttpRequest()
  xhr.open('GET', url)
  xhr.send()

  xhr.onload = () => {
    if (xhr.status === 200) {
      // 서버의 응답을 콜백 함수에 전달하면서 호출하여 응답에 대한 후속 처리를 한다.
      callback(JSON.parse(xhr.response))
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`)
    }
  }
}

const url = 'https://jsonplaceholder.typicode.com'

// id가 1인 post의 userId를 취득
get(`${url}/posts/1`, ({ userId }) => {
  console.log(userId) // 1
  // post의 userId를 사용하여 user 정보를 취득
  get(`${url}/users/${userId}`, userInfo => {
    console.log(userInfo) // {id: 1, name: "Leanne Graham", username: "Bret",...}
  })
})
```
콜벡헬은 가독성을 나쁘게하고 실수를 유발한다.
```js
get('/step1', a => {
  get(`/step2/${a}`, b => {
    get(`/step3/${b}`, c => {
      get(`/step4/${c}`, d => {
        console.log(d)
      })
    })
  })
})
```
### 45.1.2 에러 처리의 한계
콜백 패턴의 문제점중 가장 심각한것은 에러 처리가 고란하다는 것이다.
```js
try {
  setTimeout(() => { throw new Error('Error!') }, 1000)
} catch (e) {
  // 에러를 캐치하지 못한다
  console.error('캐치한 에러', e)
}
```
setTimeout 함수의 콜백 함수가 실행 될 떄는 이미 콜스택에서 제거된 상태로 콜백 함수의 호출자가 setTimeout 함수가 아니다. **에러는 호출자 방향**으로 전파된다. setTimeout 함수의 콜백 함수가 발생시킨 에러는 catch 블록에서 캐치되지 않는다.
## 45.2 프로미스의 생성
Promise 생성자 함수를 new 연산자와 함꼐 호출하면 프로미스를 생성한다. ES6에서 도입된 Promise는 호스트 객체가 아닌 ECMAScript 사양에 정의된 표준 빌트인 객체다.   
Promise 생성자 함수는 비동기 처리를 수행할 콜백 함수를 인수로 전달 받는다. 콜백 함수는 resolve와 reject 함수를 인수로 전달 받는다.
```js
// 프로미스 생성
const promise = new Promise((resolve, reject) => {
  // Promise 함수의 콜백 함수 내부에서 비동기 처리를 수행한다.
  if (/* 비동기 처리 성공 */) {
    resolve('result')
  } else { /* 비동기 처리 실패 */
    reject('failure reason')
  }
})
```
인수로 전달받은 콜백 함수 내부에서 비동기 처리를 수행한다. 비동기 처리가 성공하면 콜백함수의 인수로 전달받은 resolve 함수를 호출하고 실패하면 reject 함수를 호출한다.
```js
// GET 요청을 위한 비동기 함수
const promiseGet = url => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest()
    xhr.open('GET', url)
    xhr.send()

    xhr.onload = () => {
      if (xhr.status === 200) {
        // 성공적으로 응답을 전달받으면 resolve 함수를 호출한다.
        resolve(JSON.parse(xhr.response))
      } else {
        // 에러 처리를 위해 reject 함수를 호출한다.
        reject(new Error(xhr.status))
      }
    }
  })
}

// promiseGet 함수는 프로미스를 반환한다.
promiseGet('https://jsonplaceholder.typicode.com/posts/1')
```
비동기 처리가 성공하면 비동기 처리 결과를 resolve 함수 인수로 전달하면서 호출하고, 비동기 처리가 실패하면 에러를 reject 함수에 인수로 전달하면서 호출한다.   
|프로미스의 상태 정보|의미|상태 변경 조건|
|---|---|---|
|pending|비동기 처리가 아직 수행되지 않은 상태|프로미스가 생성된 직후 기본 상태|
|fulfilled|비동기 처리가 수행된 상태(성공)|resolve 함수 호출|
|rejected|비동기 처리가 수행된 상태(실페)|reject 함수 호출|

생성된 직후 프로미스는 기본적으로 pending 상태며 비동기 처리 결과에 따라 상태가 변경된다.
- 비동기 처리 성공: resolve 함수를 호출해 프로미스를 fulfilled 상태로 변경
- 비동기 처리 실패: reject 함수를 호출해 프로미스를 rejected 상태로 변경

fulfilled, rejected 상태를 settled 상태라 한다. settled 상태는 다른 상태로 변화할 수 없다.   
**프로미스는 비동기 처리 상태와 처리 결과를 관리하는 객체다.**
## 45.3 프로미스의 후속 처리 메서드
프로미스 비동기 처리 상태가 변화하면 이에 따른 후속 처리를 한다. 이를 위해 프로미스는 후속 메서드 then, catch, finally를 제공한다.   
**프로미스의 비동기 처리 상태가 변화하면 후속 처리 메서드에 인수로 전달한 콜백 함수가 선택적으로 호출된다.**   
모든 후속 처리 메서드는 프로미스를 반환하며 비동기로 동작한다.
### 45.3.1 Promise.prototype.then
- 첫번쨰 콜백 함수는 프로미스가 fulfilled상태가 되면 호출된다. 이떄 콜백 함수는 프로미스의 비동기 처리 결과를 인수로 전달받는다.
- 두번째 콜백 함수는 프로미스가 rejected상태가 되면 호출된다. 이떄 콜백 함수는 프로미스 에러를 인수로 전달받는다.
```js
// fulfilled
new Promise(resolve => resolve('fulfilled'))
  .then(v => console.log(v), e => console.error(e)) // fulfilled

// rejected
new Promise((_, reject) => reject(new Error('rejected')))
  .then(v => console.log(v), e => console.error(e)) // Error: rejected
```
### 45.3.2 Promise.prototype.catch
한개의 콜백 함수를 인수로 전달받아 rejected 상태인 경우 호출된다.
```js
// rejected
new Promise((_, reject) => reject(new Error('rejected')))
  .catch(e => console.log(e)) // Error: rejected
```
catch 메서드는 then(undefined, onRejected)과 동일하게 동작한다. 따라서 언제나 프로미스를 반환한다.
```js
// rejected
new Promise((_, reject) => reject(new Error('rejected')))
  .then(undefined, e => console.log(e)) // Error: rejected
```
### 45.3.3 Promise.prototype.finally
한개의 콜백 함수를 인수로 전달받아 프로미스의 성공또는 실패와 상관없이 무조건 한번 호출된다. 프로미스의 상태와 상관없이 공통적으로 수행해야할 처리 내용이 있을 떄 유용하다.
```js
new Promise(() => {})
  .finally(() => console.log('finally')) // finally
```
프로미스로 구현한 비동기 함수 get을 사용해 후속처리를 구현할 수 있다.
```js
const promiseGet = url => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest()
    xhr.open('GET', url)
    xhr.send()

    xhr.onload = () => {
      if (xhr.status === 200) {
        // 성공적으로 응답을 전달받으면 resolve 함수를 호출한다.
        resolve(JSON.parse(xhr.response))
      } else {
        // 에러 처리를 위해 reject 함수를 호출한다.
        reject(new Error(xhr.status))
      }
    }
  })
}

// promiseGet 함수는 프로미스를 반환한다.
promiseGet('https://jsonplaceholder.typicode.com/posts/1')
  .then(res => console.log(res))
  .catch(err => console.error(err))
  .finally(() => console.log('Bye!'))
```
## 45.4 프로미스의 에러 처리
프로미스는 콜백 패턴의 에러처리문제를 then, catch, filnally를 사용해 해결할 수 있다.
then 메서드의 두 번째 콜백 함수로 처리할 수 있다.
```js
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1'

// 부적절한 URL이 지정되었기 때문에 에러가 발생한다.
promiseGet(wrongUrl).then(
  res => console.log(res),
  err => console.error(err)
) // Error: 404
```
catch를 사용해 처리할 수 있다.
```js
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1'

// 부적절한 URL이 지정되었기 때문에 에러가 발생한다.
promiseGet(wrongUrl)
  .then(res => console.log(res))
  .catch(err => console.error(err)) // Error: 404
```
then의 두번쨰 콜백함수는 첫번쨰 콜백함수에서 발생한 에러를 캐치하지 못하고 코드가 복잡해져 가독성이 좋지 않다.
```js
promiseGet('https://jsonplaceholder.typicode.com/todos/1').then(
  res => console.xxx(res),
  err => console.error(err)
) // 두 번째 콜백 함수는 첫 번째 콜백 함수에서 발생한 에러를 캐치하지 못한다.
```
catch를 사용하면 비동기  처리에서 발생한 에러 뿐 아니라 then 메서드 내부에서 발생한 에러까지 캐치할 수 있다.
```js
promiseGet('https://jsonplaceholder.typicode.com/todos/1')
  .then(res => console.xxx(res))
  .catch(err => console.error(err)) // TypeError: console.xxx is not a function
```
따라서 catch의 가독성이 좋다. 에러처리에는 then 말고 catch를 사용할 것을 권장한다.
## 45.5 프로미스 체이닝
프로미스는 콜백헬을 해결한다.
```js
const url = 'https://jsonplaceholder.typicode.com'

// id가 1인 post의 userId를 취득
promiseGet(`${url}/posts/1`)
  // 취득한 post의 userId로 user 정보를 취득
  .then(({ userId }) => promiseGet(`${url}/users/${userId}`))
  .then(userInfo => console.log(userInfo))
  .catch(err => console.error(err))
```
then -> then -> catch 순서로 후속 처리 메서드를 호출한다. then, catch, finally는 언제나 프로미스를 반환하므로 연속으로 호출할 수 있다. 이를 **프로미스 체이닝**이라 한다. 
|후속 처리 메서드|콜백 함수의 인수|후속 처리 메서드의 반환값|
|---|---|---|
|then|promiseGet 함수가 반환한 프로미스가 resolve한 값|콜백 함수가 반환한 프로미스|
|then|첫번째 then 메서드가 반환한 프로미스가 resolve한 값|콜백 함수가 반환한 값을 resolve한 프로미스|
|catch|promiseGet 함수 또는 앞선 후속 처리 메서드가 반환한 프로미스가 reject한 값|콜백 함수가 반환한 값을 resolve한 프로미스|

프로미스는 프로미스 체이닝을 통해 비동기 처리 결과를 전달받아 후속 처리하므로 비동기 처리를 위한 콜백 패턴에서 발생하는 콜백헬이 발생하지 않는다.   
프로미스에서도 콜백 패턴을 사용하므로 콜백 함수를 사용하지 않는 것은 아니다. 이는 ES8에서 도입된 async/await을 통해 해결할 수 있다.
## 45.6 프로미스의 정적 메서드
Promise는 주로 생성자 함수로 사용되지만 함수도 객체이므로 메서드를 가질 수 있다.
### 45.6.1 Promise.resolve / Promise.reject
이미 존재하는 값을 래핑하여 프로미스를 생성하기 위해 사용한다.   
Promise.resolve 메서드는 인수로 전달받은 값을 resolve 하는 프로미스를 생성한다.
```js
// 배열을 resolve하는 프로미스를 생성
const resolvedPromise = Promise.resolve([1, 2, 3])
resolvedPromise.then(console.log) // [1, 2, 3]
```
위 예제는 다음과 같이 동작한다.
```js
const resolvedPromise = new Promise(resolve => resolve([1, 2, 3]))
resolvedPromise.then(console.log) // [1, 2, 3]
```
Promise.reject 메서드는 인수로 전달받은 값을 reject하는 프로미스를 생성한다.
```js
// 에러 객체를 reject하는 프로미스를 생성
const rejectedPromise = Promise.reject(new Error('Error!'))
rejectedPromise.catch(console.log) // Error: Error!
```
위 예제는 다음과같이 동작한다.
```js
const rejectedPromise = new Promise((_, reject) => reject(new Error('Error!')))
rejectedPromise.catch(console.log) // Error: Error!
```
### 45.6.2 Promise.all
Promise.all은 여러개의 비동기 처리를 병렬로 처리할 떄 사용한다.
```js
const requestData1 = () => new Promise(resolve => setTimeout(() => resolve(1), 3000))
const requestData2 = () => new Promise(resolve => setTimeout(() => resolve(2), 2000))
const requestData3 = () => new Promise(resolve => setTimeout(() => resolve(3), 1000))

// 세 개의 비동기 처리를 순차적으로 처리
const res = []
requestData1()
  .then(data => {
    res.push(data)
    return requestData2()
  })
  .then(data => {
    res.push(data)
    return requestData3()
  })
  .then(data => {
    res.push(data)
    console.log(res) // [1, 2, 3] ⇒ 약 6초 소요
  })
  .catch(console.error)
```
위 예제는 세개의 비동기 처리를 순차적으로 처리한다. 따라서 총 6초 이상이 소요된다.   
세개의 비동기 처리는 서로 의존하지 않고 개별적으로 수행된다. 따라서 처리 결과를 다음 비동기에 사용하지 않고 순차적으로 처리할 필요가 없다.   
```js
const requestData1 = () => new Promise(resolve => setTimeout(() => resolve(1), 3000))
const requestData2 = () => new Promise(resolve => setTimeout(() => resolve(2), 2000))
const requestData3 = () => new Promise(resolve => setTimeout(() => resolve(3), 1000))

Promise.all([requestData1(), requestData2(), requestData3()])
  .then(console.log) // [ 1, 2, 3 ] ⇒ 약 3초 소요
  .catch(console.error)
```
Promise.all 메서드는 프로미스를 요소로 갖는 배열등의 이터러블을 인수로 전달받는다. 전달받은 모든 프로미스가 fulfilled 상태가 되면 모든 처리 결과를 배열에 저장해 새로운 프로미스를 반환한다. 
- 첫번쨰 프로미스는 3초 후 1을 resolve한다.
- 두번째 프로미스는 2초 후 2를 resolve한다.
- 세번쨰 프로미스는 1초 후 3을 resolve한다.

전달받은 프로미스가 모두 fulfilled 상태가 되면 종료한다. 따라서 Promise.all 메서드가 종료하는데 걸린 시간은 가장 늦게 fulfilled 상태가 되는 프로미스의 처리 시간보다 조금 더 길다. 따라서 3초보다 조금 더 소요된다.   
반환되는 배열은 프로미스 배열의 순서 그래도 배열에 저장해 새로운 프로미스를 반환한다. 즉 처리 순서가 보장된다.   
인수로 전달받은 배열의 프로미스가 하나라도 rejected 상태가 되면 나머지 프로미스가 fulfilled 상태가 되는것을 기다리지 않고 즉시 종료된다.
```js
Promise.all([
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error 1')), 3000)),
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error 2')), 2000)),
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error 3')), 1000))
])
  .then(console.log)
  .catch(console.log) // Error: Error 3
```
위 예제에서 세번째 프로미스가 가장먼저 rejected 상태가 되므로 세번쨰 프로미스가 reject한 에러가 catch의 인수로 전달된다.   
Promise.all메서드는 인수로 전달받은 이터러블 요소가 프로미스가 아닌경우 Promise.resolve 메서드를 통해 프로미스로 래핑한다.
```js
Promise.all([
  1, // => Promise.resolve(1)
  2, // => Promise.resolve(2)
  3  // => Promise.resolve(3)
])
  .then(console.log) // [1, 2, 3]
  .catch(console.log)
```
### 45.6.3 Promise.race
Promise.race는 Promise.all와 동일하게 프로미스를 요소로 갖는 배열등의 이터러블은 전달받아 가장먼저 fulfilled 상태가된 프로미스의 처리 결과를 resilve하는 새로운 프로미스를 반환한다.
```js
Promise.race([
  new Promise(resolve => setTimeout(() => resolve(1), 3000)), // 1
  new Promise(resolve => setTimeout(() => resolve(2), 2000)), // 2
  new Promise(resolve => setTimeout(() => resolve(3), 1000)) // 3
])
  .then(console.log) // 3
  .catch(console.log)
```
프로미스가 rejected 상태가 되면 Promise.all 메서드와 동일하게 처리된다.
```js
Promise.race([
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error 1')), 3000)),
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error 2')), 2000)),
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error 3')), 1000))
])
  .then(console.log)
  .catch(console.log) // Error: Error 3
```
### 45.6.4 Promise.allSettled
Promise.allSettled는 프로미스를 요소로 갖는 배열등의 이터러블은 전달받아 모두 settled상태가 되면 처리 결과를 배열로 반환한다. ES11에서 도입된 Promise.allSettled는 대부분의 모던 브라우저에서 지원한다.
```js
Promise.allSettled([
  new Promise(resolve => setTimeout(() => resolve(1), 2000)),
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error!')), 1000))
]).then(console.log)
/*
[
  {status: "fulfilled", value: 1},
  {status: "rejected", reason: Error: Error! at <anonymous>:3:54}
]
*/
```
Promise.allSettled 메서드가 반환한 배열은 fulfillec, rejected 상관없이 Promise.allSettled 메서드의 인수로 전달받은 모든 프로미스들의 처리 결과가 담겨있다.
- 프로미스가 fulfilled상태인 경우 비동기 처리 상태를 나타내는 status 프로퍼티와 처리 결과를 나타내는 value 프로퍼티를 갖는다.
- 프로미스가 rejected 상태인 경우 비동기 처리 상태를 나타내는 status 프로퍼티와 에러를 나타내는 reason 프로퍼티를 갖는다.
## 45.7 마이크로태스크 
```js
setTimeout(() => console.log(1), 0)

Promise.resolve()
  .then(() => console.log(2))
  .then(() => console.log(3))
```
프로미스 후속 처리 메서드도 비동기로 동작하므로 1->2->3의 순으로 출력될 것 같지만 2->3->1로 출력된다. 프로미스의 후속  처리 메서드의 콜백함수는 테스크 큐가 아니라 마이크로테스크 큐에 저장되기 때문이다.
마이크로테스크 큐에는 프로미스의 후속처리 메서드의 콜백함수가 일시 저장된다. 그외 비동기 함수의 콜백함수나 이벤트핸들러는 테스크큐에 일시 저장된다.   
**마이크로테스크 큐는 테스크 큐보다 우선순위가 높다.** 즉, 이벤트 루프는 콜 스택이 비면 먼저 마이스로테스크 큐에서 대기하고 있는 함수를 가져와 실행하고 마이크로테스크 큐가 비면 테스크 큐에서 대기하고 있는 함수를 가져와 실행한다.
## 45.8 fetch
fetch는 HTTP 요청 전송 기능을 제공하는 클라이언트 사이드 Web API다. fetch는 대부분의 모던 브라우저에서 제공한다.   
fetch 함수에는 HTTP 요청을 전송할 URL과 HTTP 요청 메서드, HTTP 요청 헤더, 페이로드 등을 설정한 객체를 전달한다.   
**fetch 함수는 HTTP 응답을 나타내는 Response 객체를 래핑한 Promise 객체를 반환한다.** 
```js
fetch('https://jsonplaceholder.typicode.com/todos/1')
  .then(response => console.log(response))
```
Response.prototype에는 Response 객체에 포함된 HTTP 응답 몸체를 위한 다양한 메서드를 제공한다. fetch 함수가 반환한 프로미스가 래핑하고 있는 MIME 타입이 application.json인 HTTP 응답 몸체를 취하려면 Response.prototype.json 메서드를 사용한다. prototype.json메서드는 Response 객체에서 HTTP 응답 몸체를 취득하여 역직렬화한다.
```js
fetch('https://jsonplaceholder.typicode.com/todos/1')
  // response는 HTTP 응답을 나타내는 Response 객체이다.
  // json 메서드를 사용하여 Response 객체에서 HTTP 응답 몸체를 취득하여 역직렬화한다.
  .then(response => response.json())
  // json은 역직렬화된 HTTP 응답 몸체이다.
  .then(json => console.log(json))
  // {userId: 1, id: 1, title: "delectus aut autem", completed: false}
```
fetch를 사용할떄 에러처리를 주의해야 한다.
```js
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1'

// 부적절한 URL이 지정되었기 때문에 404 Not Found 에러가 발생한다.
fetch(wrongUrl)
  .then(() => console.log('ok'))
  .catch(() => console.log('error'))
```
잘못된 URL이라 404에러가 발생하고 catch에 의해 error가 출력될 것 같지만 ok가 출력된다.
**fetch 함수가 반환하는 프로미스는 404나 500 에러와 같은 HTTP 에러가 발생해도 에러를 reject하지 않고 불리언 타입의 ok 상태를 false로 설정한 Response 객체를 resolve한다. 오프라인등의 네트워크 장애나 CORS 에러에 의해 요청이 완료되지 못한 경우에만 프로미스를 reject한다.**   
따라서 fetch 함수를 사용할 떄는 다음과 같은 fetch 훔수가 반환한 프로미스가 resolve한 불리언 타입의 ok 상태를 확인해 명시적으로 에러를 처리해야한다.
```js
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1'

// 부적절한 URL이 지정되었기 때문에 404 Not Found 에러가 발생한다.
fetch(wrongUrl)
  // response는 HTTP 응답을 나타내는 Response 객체다.
  .then(response => {
    if (!response.ok) throw new Error(response.statusText)
    return response.json()
  })
  .then(todo => console.log(todo))
  .catch(err => console.error(err))
```
axios는 모든 HTTP 에러를 reject하는 프로미스를 반환한다. 모든 에러를 catch에서 처리할 수 있어 편리하다.    
```js
const request = {
  get(url) {
    return fetch(url)
  },
  post(url, payload) {
    return fetch(url, {
      method: 'POST',
      headers: { 'content-Type': 'application/json' },
      body: JSON.stringify(payload)
    })
  },
  patch(url, payload) {
    return fetch(url, {
      method: 'PATCH',
      headers: { 'content-Type': 'application/json' },
      body: JSON.stringify(payload)
    })
  },
  delete(url) {
    return fetch(url, { method: 'DELETE' })
  }
}
```
#### 1. GET 요청
```js
request.get('https://jsonplaceholder.typicode.com/todos/1')
  .then(response => {
    if (!response.ok) throw new Error(response.statusText)
    return response.json()
  })
  .then(todos => console.log(todos))
  .catch(err => console.error(err))
// {userId: 1, id: 1, title: "delectus aut autem", completed: false}
```
#### 2. POST 요청
```js
request.post('https://jsonplaceholder.typicode.com/todos', {
  userId: 1,
  title: 'JavaScript',
  completed: false
}).then(response => {
    if (!response.ok) throw new Error(response.statusText)
    return response.json()
  })
  .then(todos => console.log(todos))
  .catch(err => console.error(err))
// {userId: 1, title: "JavaScript", completed: false, id: 201}
```
#### 3. PATCH 요청
```js
request.patch('https://jsonplaceholder.typicode.com/todos/1', {
  completed: true
}).then(response => {
    if (!response.ok) throw new Error(response.statusText)
    return response.json()
  })
  .then(todos => console.log(todos))
  .catch(err => console.error(err))
// {userId: 1, id: 1, title: "delectus aut autem", completed: true}
```
#### 4. DELETE 요청
```js
request.delete('https://jsonplaceholder.typicode.com/todos/1')
  .then(response => {
    if (!response.ok) throw new Error(response.statusText)
    return response.json()
  })
  .then(todos => console.log(todos))
  .catch(err => console.error(err))
// {}
```